# Generated by Django 5.1.2 on 2024-11-22 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_city_org_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile1',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='profile2',
        ),
        migrations.AddField(
            model_name='friend',
            name='org1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org1', to='project.org'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='org2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org2', to='project.org'),
            preserve_default=False,
        ),
    ]
