# Generated by Django 5.1.2 on 2024-11-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_inventoryitem_available_sizes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmessage',
            old_name='profile',
            new_name='org',
        ),
    ]
