# Generated by Django 5.1.2 on 2024-11-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rental_buyer_rental_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='org',
        ),
    ]
