# Generated by Django 5.1.2 on 2024-12-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_org_venmo_username_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='prop',
            field=models.PositiveIntegerField(default=0, verbose_name='Prop or Other Quantity'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='usage_type',
            field=models.CharField(choices=[('rent', 'For Rent'), ('storage', 'For Storage')], default='storage', max_length=10),
        ),
        migrations.AlterField(
            model_name='org',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
