# Generated by Django 5.1.2 on 2024-12-10 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_statusmessage_org_delete_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='rental_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='project.rental'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(),
        ),
    ]
