# Generated by Django 5.1.2 on 2024-12-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_inventoryitem_rental_status_alter_rental_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='rental_status',
        ),
    ]
