# Generated by Django 5.1.2 on 2024-10-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_statusmessage_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='image_file',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
