# Generated by Django 5.1.2 on 2024-10-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0008_alter_image_image_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
